apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-api
  template:
    metadata:
      labels:
        app: inventory-api
    spec:
      containers:
        - name: inventory-api
          image: mfraj1/inventory-api:latest

          env:
            - name: POSTGRES_DB
              value: inventory
            - name: POSTGRES_USER
              value: inventory
            - name: POSTGRES_PASSWORD
              value: inventorypass
          ports:
            - containerPort: 5000
