apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-db
  template:
    metadata:
      labels:
        app: inventory-db
    spec:
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: POSTGRES_USER
              value: inventory
            - name: POSTGRES_PASSWORD
              value: inventorypass
            - name: POSTGRES_DB
              value: inventory
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
      volumes:
        - name: init-script
          configMap:
            name: postgres-init
